services:
  app:
    build: .
    container_name: vimmo_app
    ports:
      - "5000:5000"  # Map host port 5001 to container port 5001
    volumes:
      - ./vimmo/db:/app/vimmo/db  # Mount local db directory into the container's db directory
    environment:
      - DATABASE_URL=/app/vimmo/db/panels_data.db  # Set environment variable for database path (optional, for explicit reference)
    command: ["/bin/bash", "-c", "source ~/.bashrc && conda activate VIMMO && vimmo"]  # Run the Flask app in the container

volumes:
  db_data:  # This volume is for persisting the database